/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "background": "#faf8ff",
        "surface": "#faf8ff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f2f3ff",
        "surface-container": "#eaedff",
        "surface-container-high": "#e2e7ff",
        "surface-variant": "#dae2fd",
        "primary": "#00288e",
        "on-primary": "#ffffff",
        "primary-container": "#1e40af",
        "primary-fixed": "#dde1ff",
        "on-primary-fixed": "#001453",
        "secondary": "#006c4a",
        "on-secondary": "#ffffff",
        "secondary-container": "#82f5c1",
        "tertiary": "#440098",
        "on-tertiary": "#ffffff",
        "tertiary-fixed": "#eaddff",
        "on-tertiary-fixed": "#25005a",
        "error": "#ba1a1a",
        "on-surface": "#131b2e",
        "on-surface-variant": "#444653",
        "outline": "#757684",
        "outline-variant": "#c4c5d5",
      },
      spacing: {
        "space-2xs": "0.25rem",
        "space-xs": "0.5rem",
        "space-sm": "0.75rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2rem",
        "space-2xl": "3rem",
        "gutter-mobile": "1rem",
        "gutter-desktop": "1.5rem",
        "layout-container-max": "1280px",
      },
      fontFamily: {
        "headline-xl": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "body-regular": ["Inter", "sans-serif"],
        "body-compact": ["Inter", "sans-serif"],
        "metadata-label": ["Inter", "sans-serif"],
        "tag-chip": ["Inter", "sans-serif"],
        "job-title-card": ["Inter", "sans-serif"],
      },
      fontSize: {
        "headline-xl": ["36px", { lineHeight: "44px", fontWeight: "700", letterSpacing: "-0.02em" }],
        "headline-lg": ["24px", { lineHeight: "32px", fontWeight: "700", letterSpacing: "-0.015em" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600", letterSpacing: "-0.01em" }],
        "body-regular": ["14px", { lineHeight: "22px", fontWeight: "400" }],
        "body-compact": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "metadata-label": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "tag-chip": ["11px", { lineHeight: "14px", fontWeight: "500", letterSpacing: "0.02em" }],
        "job-title-card": ["16px", { lineHeight: "24px", fontWeight: "600" }],
      }
    },
  },
  plugins: [],
}